# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ayushi Dutta
tagline:             'MS by Research, IIIT Hyderabad'
description:         'A <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme called <a href="http://jekyllrb.com" target="_blank">Lanyon</a>, made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ayushi Dutta
  url:               https://twitter.com/ayushidutta
  email:             ayushi.dutta@research.iiit.ac.in

# Custom vars
version:             1.0.0
